import ListingContainer from './(component)/ListingContainer';
import { ListingResponse } from './interface';

function listingGenerator(): ListingResponse {
  return {
    items: [
      {
        id: '300003002904591-jobsdb',
        platformId: '300003002904591',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/spares-and-c-a-operations-data-specialist-300003002904591',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Spares and C&A Operations Data Specialist',
        company: 'Electrolux Thailand Co., Ltd.',
        postDate: '2023-08-30T23:00:00Z',
        jobDescription: [
          'Flexible work hours/hybrid work environment',
          'Discounts on Electrolux products and services',
          'Great career development & learning opportunities',
          'You are a part of the operations team and will be working closely with both planning & warehouse functions responsible for Spare Parts, Consumables & Accessories and play a vital role in the success of delivering better consumer experiences.',
          'The Spares & C&A Operations Data Specialist will be responsible to create and maintain master data in SAP and related systems covering processes like item registration, item extensions, interchangeability management and more.',
          'The role is a key enabler for success within the operations team and works closely with planning and warehouse teams.',
          'You monitor, report performance, and execute data services and ensure the highest level of data quality is going into our systems. You are also collaborating with your manager and peers on how to improve the ways of working to achieve an even higher level of data quality and improve the lead-time of process execution.',
          'You analyze the assortments and interact with peers across the regions to find answer should there be a deviation. You also participate in cross functional projects and initiatives related to the master data function.',
          'Creating and maintaining master data in SAP and other relevant systems.',
          'Working in different projects and initiatives in the function of master data, like master data cleansing.',
          'Together with your colleagues you will continuously improve the ways of working',
          'Help shaping business requirements for IT in order to improve the systems and workflows',
          'Responsible to monitor and report on performance in your functional area',
          'Drive adherence to the polices and guidelines for master data and ensure related documentation is always up to date.',
          'Collaborate with stakeholders across the organization and implement data related projects and initiatives.',
          'The successful candidate is highly analytical and has an eye for details, understand the impact of master data in the business processes and applies a strong level of structure and discipline to the ways of working. You feel comfortable highlighting gaps in a constructive way and have a drive to continuously improve the ways of working. You enjoy working in a team environment and understand how your individual work contributes to the overall team’s performance. The ideal candidate has very good technical skills related to data and analysis and takes pride in ensuring quality of data.',
          'Bachelor’s Degree in information management, Computer Science or related field.',
          'Solid knowledge of SAP Data Management',
          'Understanding of master data and its impact across the organization.',
          'Analytical skills and drive actions based on facts in a structured way.',
          'Fluent in English both written & spoken.',
          'Takes initiative to solve problems and drive until completion. ',
          'Good computer application skills. (i.e. Word, Excel, power point, etc.)',
          'Exceptional understanding of technical solutions related to data and analysis',
          'Ability to represent the organization with integrity and professionalism.',
          'You will be based in Thailand, and work from our office in Bangkok.',
          'Flexible working hours with hybrid work schedule.',
          'International environment.',
          'Discounts on Electrolux products and services.',
          'Medical & Hospitalization coverage for both employees and dependents.',
          'https://career.electroluxgroup.com/global/en',
          'Full Time, Permanent',
          'Middle',
        ],
        benefit: [
          'Dental insurance',
          'Life insurance',
          'Medical insurance',
          'Performance bonus',
          'Work from home',
          'Five-day work week',
          'Flexible working hours',
        ],
        industry: 'Electronics/Electrical Equipment',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002912699-jobsdb',
        platformId: '300003002912699',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/data-scientist-300003002912699',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Data Scientist',
        company: 'Siam Commercial Bank Public Co., Ltd.',
        postDate: '2023-08-30T18:39:12Z',
        jobDescription: [
          'Work from Anywhere Policy (Hybrid)',
          'Fresh graduate is welcomed',
          'Analyze data, extract insights, and create model',
          'Apply statistical and machine learning methods to large, complex data sets to draw insights and provide actionable recommendations.',
          'Solve complex problems on both technical and business sides using advanced analytical methods.',
          'Work with Engineering teams to implement end-to-end process from model development to testing, validation, and deployment',
          'Research and develop new quantitative models and frameworks to enhance the company’s data science capability',
          'Bachelor’s degree in Engineering, Computer Science, Math, Physics, Statistics or other areas that are highly quantitative',
          'Experience with statistical programming languages (e.g., Python, R, pandas) and database software (e.g., SQL, PySpark)',
          'Knowledge in statistics (e.g., hypothesis testing, regression) and machine learning',
          'Strong analytical problem-solving capabilities',
          'Master’s or PhD degree in a quantitative discipline',
          'Experience applying machine learning and statistical methods to large datasets',
          'Solid understanding of advanced statistics and machine learning practices.',
          'Experience in one or more specialized machine learning areas (e.g., NLP, deep learning, recommendation systems, reinforcement learning)',
          'Outstanding coding skills or software development background.',
          'Ability to think independently and communicate complex ideas to less technical persons',
          'Excellent command of English in both verbal and written forms',
          'Full Time',
          'Entry Level',
        ],
        benefit: [
          'Dental insurance',
          'Medical insurance',
          'Performance bonus',
          'Work from home',
          'Five-day work week',
          'Flexible working hours',
        ],
        industry: 'Financial Services',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002908539-jobsdb',
        platformId: '300003002908539',
        pageUrl: 'https://th.jobsdb.com/th/en/job/qa-lead-300003002908539',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'QA Lead',
        company:
          'Thai Credit Retail Bank Public Company Limited/ ธนาคารไทยเครดิต เพื่อรายย่อย จำกัด (มหาชน)',
        postDate: '2023-08-30T18:38:16Z',
        jobDescription: [
          'Proficient in test automation tools.',
          'Lead and manage a team of QA engineers',
          'Develop and implement quality assurance processes',
          'Lead and manage a team of QA engineers, providing guidance, mentoring, and support to ensure efficient and effective testing activities.',
          'Develop and implement quality assurance processes and strategies to ensure software products meet or exceed specified quality standards.',
          'Define and execute test plans, test cases, and test scripts to validate software functionality, performance, reliability, and scalability.',
          'Collaborate with cross-functional teams, including development, product management, and project management, to identify quality gaps, recommend improvements, and drive issue resolution.',
          'Continuously assess and improve the effectiveness and efficiency of the QA processes, tools, and methodologies.',
          'Stay up-to-date with industry best practices, emerging trends, and latest technologies related to software testing and quality assurance.',
          'Conduct regular team meetings, provide feedback, and facilitate knowledge sharing sessions to encourage growth and development within the QA team.',
          'Establish and maintain strong working relationships with stakeholders, ensuring clear communication and transparency regarding quality assurance activities and progress.',
          'Prepare and present reports on quality metrics, test coverage, and test results to management and project teams.',
          'Participate in the recruitment and selection process for QA team members, ensuring the right skillsets and talents are acquired.',
          "Bachelor's degree in Computer Science, Engineering, or related discipline.",
          'Proven experience as a QA Lead or similar role, with a strong background in software quality assurance.',
          'In-depth knowledge of software testing methodologies, tools, and best practices.',
          'Strong leadership skills with the ability to effectively manage and motivate a team.',
          'Excellent analytical and problem-solving abilities, with keen attention to detail.',
          'Solid understanding of Agile methodologies and experience working in Agile teams.',
          'Strong communication skills, both written and verbal, with the ability to effectively collaborate with cross-functional teams.',
          'Proficient in test automation tools.',
          'Proficient in using test management and defect tracking tools.Certification in software testing (e.g., ISTQB, CSTE) is preferred.',
          'Experience in the industry/domain related to the software being developed is a plus.',
          'Permanent',
          'Senior',
        ],
        benefit: [
          'Dental insurance',
          'Life insurance',
          'Medical insurance',
          'Performance bonus',
          'Five-day work week',
        ],
        industry: 'Financial Services',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002908323-jobsdb',
        platformId: '300003002908323',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/senior-software-developer-full-stack-developer-300003002908323',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Senior Software Developer (Full stack developer)',
        company: 'SVI Public Company Limited',
        postDate: '2023-08-30T18:37:42Z',
        jobDescription: [
          'Full stack developer',
          'Python',
          'Senior Software Developer',
          'Full Time',
          'Senior',
        ],
        benefit: [
          'Free shuttle bus',
          'Life insurance',
          'Medical insurance',
          'Performance bonus',
          'Five-day work week',
        ],
        industry: 'Electronics/Electrical Equipment',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002908220-jobsdb',
        platformId: '300003002908220',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/programmer-%E0%B9%82%E0%B8%9B%E0%B8%A3%E0%B9%81%E0%B8%81%E0%B8%A3%E0%B8%A1%E0%B9%80%E0%B8%A1%E0%B8%AD%E0%B8%A3%E0%B9%8C-300003002908220',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Programmer/โปรแกรมเมอร์',
        company: 'BEC World Public Co., Ltd.',
        postDate: '2023-08-30T18:37:24Z',
        jobDescription: [
          'Programmer',
          'โปรแกรมเมอร์',
          'IT',
          'Bachelor’s degree of Computer Engineering/Computer Science/Software Engineering-Information Technology/Information System or any IT related fields',
          'Minimum of 3-5 years of experience inProgamming, coding, or software development for HTML, jQuery, CSS, JavaScript, Ajax,PHP and/or C#.Net',
          'Strong knowledge of design and develop web/Mobile  applications by Javascript , Jdeveloper, Oracle Report, PL/SQL, WebLogic technology.',
          'Strong Knowledge of JAVA, C++, Phyton, SQL, and Oracle Database',
          ' Able to work under pressure, good team player, and good coordination skills.',
          'Communication and Interpersonal skills',
          'Problem solving skills',
          'Teamwork',
          'Responsibility',
          'Flexibility',
          'Service mind',
          'To code the new application and modification system program to be used in the company.',
          'To create a new application system manual and cooperate for the training program to the user.',
          'To coordinate for system set up after developed together with examining, and survey for checking the feedback',
          'To coordinate system production according to the system requirement of the business office.',
          'To ensure that all coding are delivered on-time and within scope',
          'To perform other related duties as assigned',
          'Full Time',
        ],
        benefit: [],
        industry: 'Advertising/Public Relations/Marketing Services',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002903701-jobsdb',
        platformId: '300003002903701',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/junior-full-stack-developer-%5Bj047%5D-300003002903701',
        salaryMin: 20000,
        salaryMax: 35000,
        currency: 'THB',
        jobTitle: 'Junior Full Stack Developer  [J047]',
        company: 'OpenDurian Co., Ltd.',
        postDate: '2023-08-29T23:00:00Z',
        jobDescription: [
          'เปิดกว้างด้านความคิด เสนอไอเดียได้เต็มที่',
          'เน้นผลลัพธ์ ดูที่ผลงาน',
          'ออฟฟิศคนรุ่นใหม่ WFH 99%',
          'ดูแลระบบหลังบ้านและเว็บไซต์บริษัทในปัจจุบันและต่อยอดไปยังระบบอื่นๆที่เกี่ยวข้องในอนาคต',
          'พัฒนาและดูแลเว็บไซต์โดยใช้ภาษา Vue.js ด้วย Framework Nuxt2 หรือ Nuxt3',
          'พัฒนาเว็บไซต์โดยใช้ HTML, CSS, Javascript',
          'พัฒนาระบบหลังบ้านด้วยภาษา Python บน Django หรือ Flask Framework',
          'ได้ทำงานในด้าน Logic และ Algorithm',
          'สามารถเรียนรู้ภาษาใหม่ๆที่สอดคล้องกับงานนั้นๆได้ในอนาคต เช่น TypeScript, React หรืออื่นๆ',
          'มีความรู้ความเข้าใจในโครงสร้างพื้นฐานของ Database โดยเฉพาะ PostgreSQL และ MongoDB',
          'การเรียนรู้: ชอบเรียนรู้สิ่งใหม่ เรียนรู้สิ่งต่างๆได้เร็ว สามารถเรียนรู้ด้วยตนเองได้ดี และสามารถถ่ายทอดสิ่งที่ได้เรียนรู้มาให้กับทีมหรือผู้อื่นเข้าใจได้,',
          'ความรับผิดชอบ: มีความรับผิดชอบ ใส่ใจงานที่ได้รับมอบหมาย ทำงานได้ตรงตาม Scope เวลาที่กำหนด และมีความรอบคอบในการตรวจสอบงานที่รับผิดชอบ',
          'ความคิดสร้างสรรค์: คิดและตั้งคำถามกับสิ่งต่าง ๆ อย่างมีวิจารณญาณ รอบคอบ และเชื่อมโยงกับประเด็นต่าง ๆ ได้ดี,',
          'การสื่อสาร: มีความกล้าแสดงออก มีความมั่นใจในการสื่อสารหรือตั้งคำถามกับประเด็นต่างๆที่ตนสนใจหรือไม่เข้าใจหรือไม่เห็นด้วยกับประเด็นนั้นๆ',
          'เป็นคนที่มี Passion ในการเรียนรู้และอยากทำงานร่วมกันกับทีมโดยมุ่งเน้นผลลัพธ์เป็นหลัก',
          'Full Time, Permanent',
        ],
        benefit: [
          'Dental insurance',
          'Medical insurance',
          'Overtime pay',
          'Performance bonus',
          'Work from home',
          'Five-day work week',
          'Flexible working hours',
        ],
        industry: 'Education',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002903116-jobsdb',
        platformId: '300003002903116',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/fullstack-developer-300003002903116',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Fullstack Developer',
        company: 'TMBThanachart Bank or ttb / ทีเอ็มบีธนชาต หรือ ทีทีบี',
        postDate: '2023-08-29T23:00:00Z',
        jobDescription: [
          'Java',
          'Spring Boot',
          'AngularJS, ReactJS',
          'Full Time',
          'Senior',
        ],
        benefit: ['Five-day work week'],
        industry: 'Financial Services',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002903559-jobsdb',
        platformId: '300003002903559',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/front-end-developer-300003002903559',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Front-end Developer',
        company: 'TMBThanachart Bank or ttb / ทีเอ็มบีธนชาต หรือ ทีทีบี',
        postDate: '2023-08-29T23:00:00Z',
        jobDescription: [
          'Angular.JS, React.JS',
          'Working with new gen',
          'Hybrid and Flexible environment',
          'Write clean code to develop front end functional requirement',
          'Collaborate with Back-end developers to integrate user-facing elements with server side logic',
          'Participate in the entire application lifecycle, focusing on coding and debugging',
          'Gather and address technical and design requirements',
          'Test, defect fix and deploy programs to SIT, UAT and Production environment',
          'Troubleshoot and debug applications',
          'Perform UI tests to optimize performance',
          'Build reusable code and libraries for future use',
          'Follow emerging technologies',
          'Writing technical and functional documents for reference',
          'Attending scrum and team meetings',
          'Running the Change Management process',
          'Language - Angular.JS, React.JS',
          'Mobile – Android, Kotlin, Flutter',
          'Database - Postgresql, MongoDB, Oracle',
          'Windows and Linux operating systems',
          'Other - DevSecOps, jenkin, BitBucket, Nexus',
          'Optional - Openshift, AWS',
          'Full Time, Permanent, Contract',
          'Entry Level',
        ],
        benefit: [
          'Dental insurance',
          'Life insurance',
          'Medical insurance',
          'Performance bonus',
          'Five-day work week',
          'Flexible working hours',
        ],
        industry: 'Financial Services',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002903710-jobsdb',
        platformId: '300003002903710',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/database-administrator-300003002903710',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Database Administrator',
        company: 'G-Able Company Limited',
        postDate: '2023-08-29T23:00:00Z',
        jobDescription: [
          'Oracle Database, SQL Database , PostgreSQL DB',
          'SQL language / Database design',
          'Windows, Unix, Linux',
          'Installing and upgrading the database server and application tools',
          'Allocating system storage and planning future storage requirements for the database system',
          'Modifying the database structure, as necessary, from information given by application developers',
          'Enrolling users and maintaining system security',
          'Ensuring compliance with database vendor license agreement',
          'Controlling and monitoring user access to the database',
          'Monitoring and optimizing the performance of the database',
          'Planning for backup and recovery of database information',
          'Maintaining archived data',
          'Backing up and restoring databases',
          'Contacting database vendor for technical support',
          'Generating various reports by querying from database as per need',
          'Development and design of database strategies',
          'Improving database performance and capacity',
          'Bachelor’s degree in Information Technology, Computer Sciences, or related fields',
          'Minimum 2 years’ experience in MS SQL Server and Oracle Database Administration (DBA)',
          'Knowledge of database theory & database design',
          'Knowledge about the RDBMS itself, e.g. Oracle Database, SQL Database , PostgreSQL DB',
          'Knowledge of structured query language (SQL), e.g. SQL',
          'General understanding of distributed computing architectures, e.g. Client/Server, Internet/Intranet, Enterprise',
          'General understanding of the underlying operating system, e.g. Windows, Unix, Linux',
          'General understanding of routine maintenance, recovery, and handling failover of a Database',
          'Permanent, Contract',
        ],
        benefit: [
          'Dental insurance',
          'Life insurance',
          'Medical insurance',
          'Overtime pay',
          'Performance bonus',
          'Travel allowance',
          'Work from home',
          'Five-day work week',
          'Flexible working hours',
        ],
        industry: 'Information Technology',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
      {
        id: '300003002911802-jobsdb',
        platformId: '300003002911802',
        pageUrl:
          'https://th.jobsdb.com/th/en/job/programmer-java-300003002911802',
        salaryMin: null,
        salaryMax: null,
        currency: 'THB',
        jobTitle: 'Programmer (Java)',
        company: 'KTB Computer Services Co., Ltd.',
        postDate: '2023-08-29T17:17:33Z',
        jobDescription: [
          'Programmer, Web Application',
          'JAVA, C#, PHP, HTML5, JavaScript, Python',
          'งานท้าทาย องค์กรมั่นคง สวัสดิการดี',
          'Interact with the system analysts to gain understanding of the business needs and the requirements for any application requirements.',
          'Design, develop, implement, and test the new software programs and applications throughout the software development life cycle',
          'Bachelor’s degree or higher in Computer Science, Computer Engineering, IT or related fields.',
          'Strong knowledge in object-oriented design and programming.',
          '0 – 3 years experience in Java developer.',
          'Experience in IT Industry or Banking Business would be an advantage.',
          'Programming language: Java, Javascript, AJAX, JQuery.',
          'Tool and Platform: Eclipse, Netbean, JBuilder, Hibernate, Spring, Strust, J2SE, J2EE (Servlet, JSP), JBOSS, Websphere, UML',
          'Database: DB2, Oracle, PL/SQL',
          'OS: Linux, Unix, Windows',
          'Full Time',
          'Entry Level',
        ],
        benefit: [
          'Dental insurance',
          'Life insurance',
          'Medical insurance',
          'Performance bonus',
          'Work from home',
          'Five-day work week',
        ],
        industry: 'Information Technology',
        vendorId: 'jobsdb',
        vendorName: 'jobsDb',
        vendorUrl: 'https://www.jobsdb.com/',
      },
    ],
    meta: {
      totalItems: 16,
      itemCount: 10,
      itemsPerPage: 10,
      totalPages: 2,
      currentPage: 1,
    },
  };
}

export default function Home() {
  return (
    <>
      <div
        className="listing-container"
        style={{
          display: 'flex',
          backgroundColor: 'white',
          width: '70vw',
          height: '70vh',
          marginLeft: '15vw',
          marginTop: '10vh',
          color: 'black',
          cursor: 'pointer',
          boxShadow: '0px 0px 2px rgba(0, 0, 0, 0.25)',
        }}
      >
        <ListingContainer items={listingGenerator().items} />
      </div>
    </>
  );
}
