name: Pull Request Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        run: |
          cd backend
          docker build -t backend-image .
      
      - name: Run Backend Tests
        run: |
          docker run --rm backend-image npm run test

  build-and-test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Frontend Docker Image
        run: |
          cd frontend
          docker build -t frontend-image .
